import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import Script from "next/script";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script type="text/javascript" src="https://www.monetbil.com/widget/v2/monetbil.min.js"></Script>
      <body >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
